### ISSUE TITLE
Who are/will be the new community maintainers?

### ISSUE THREAD

**Issue by alerque** [mattermost-community/focalboard#4875]
Per the recent [forum announcement](https://forum.mattermost.com/t/upcoming-product-changes-to-boards-and-various-plugins/16669) and README announcement (556a9f80fbc57c396b4c0ed9abb06d5ea00a7925), this project is no longer developed by Mattermost.

The README also states that the repository here will remain:

> This Focalboard repository will remain open indefinitely for contributions from the open source community.

My question is who is going to manage community contributions? Will community volunteers be chosen to facilitate PRs and issue management? Who does/will have access to tag new releases going forward?

**Comment by alerque** [comment]
In the event you *are* looking for volunteers, I may be interested. First order of business would be to do some issue triage... this for example is not a "bug" ;-)

**Comment by dschaper** [comment]
_Crickets_

**Comment by JRDetwiler** [comment]
Does anyone know if this has been forked, or if other decent alternatives exist? I just like the progress tracker view, really.

**Comment by alerque** [comment]
There are lots of forks with one or a few fixes here or there, but before we try to gather momentum around one of them it would be *really* valuable if we could be given access to this repo or have somebody migrate it to a namespace where we can work with it a little. The existing issues and PRs are a huge asset and should not just be left behind unless they really won't work with us on this.

**Comment by alexeyqu** [comment]
Absolutely, someone from the team should follow-up on this question. "fully community supported" doesn't have much impact when the community can't have write access to the repo.

I'll try and tag @sbishel and @mgdelacroix as some of the contributors who were active recently.

I'd also be happy to contribute occasionally, e.g. recently was working on expanding the Trello exporter script to support more fields (#4874).

**Comment by sbishel** [comment]
Thanks everyone and sorry for the lack of response. 

We are going to be looking for community maintainers and potentially sponsoring enthusiastic community members. But the details are still being worked out.

Eventually, we would like to move the repo out of the mattermost repo and potentially to a community sponsor. We are still trying to figure out exactly how we want to handle this, as we are still responsible for security issues for a period of time.

**Comment by MrWaggel** [comment]
How will security be handled or guaranteed on mattermost plugins that have been moved to community?

Asking because company and partner policies disallows us to use untrusted software or sources in our environment.

**Comment by Caseum96** [comment]
Is there any update on this?

**Comment by alerque** [comment]
What is the hold up here? Are volunteers being considered? Is the possibility of blessing an existing fork with the official torch being considered?

If @mattermost is interested in a community maintainer with some existing credentials in the FOSS world (I already have access to publishing software that is running probably anywhere Focalboard would be, hence am not exactly a new security threat) then I'd be willing to step in. As I wouldn't have the time to actually take development in hand myself it would just be a facilitator role setting up CI, organizing triage, and reviewing contributions. But perhaps that could get the ball rolling again before we all end up having to migrate to something else that hasn't come along yet.

**Comment by alexeyqu** [comment]
Perhaps we can kick-start this conversation in the official Mattermost channel?
i.e. https://community.mattermost.com/core/channels/focalboard or something.

There are also some decisions by Mattermost team which I don't entirely understand.
For example, https://github.com/mattermost/mattermost-plugin-boards seems to be a new repo where the Boards product is developed actively but only as a MM plugin and only for the Enterprise version.

I hope this will not mean that standalone (community-maintained and free for personal use) Focalboard will cease to exist.

**Comment by jwilander** [comment]
Hi all, thanks for the comments and sorry for the crickets here in the last months. To give an update, we're in the process of splitting out the Mattermost Boards plugin from this repository so that we can maintain that separately for a set of our customers.

Once we do that, this repository will only contain the standalone Focalboard project and will be moved to our new `mattermost-community` GitHub org where we can then open it up for people in the community to maintain. We're hoping we can do that in about a month or so.

Once it's moved over we don't really have a process for adding maintainers but generally I think we'd be looking for volunteers who have history maintaining some projects that we could give write access to for reviewing/merging PRs, creating releases and so on.

Beyond getting maintainers access to what they need I can't promise or guarantee more support as we need this to primarily be community-driven but at the same time we'd like to be helpful and unblock folks who do want to work on it.

**Comment by alerque** [comment]
Thanks for the response and a bit of an update.

I'm sure other people are here for other reasons, but this update actually concerns me more than it puts anything to rest.

> To give an update, we're in the process of splitting out the Mattermost Boards plugin from this repository so that we can maintain that separately for a set of our customers.

My personal use case is for the plugin used on a self hosted Mattermost instance. For reasons (vendor lock-in adverse non-profit org) only self hosted FOSS solutions can be considered. Hence I'm not a customer, but do need the plugin version. I am not interested in the stand alone app variant. As mentioned above I'm willing to contribute towards Focalboard to keep it viable, but not so much in something that ends up being only available to commercial clients. I don't even know how you separate the core functionality into two repos unless the standalone one just becomes a desktop app wrapper for the web app.

So ... is Focalboard as an MM plugin going to be available to self hosted MM instances going forward? And is there a path to contribute towards *that* aspect of things?

**Comment by jwilander** [comment]
We're only providing official support for the Boards plugin to some of our customers but we currently have no plans to change the open source licensing away from what Focalboard has had all along. If we ever do stop supporting the plugin I imagine we'd be happy to spin it off, like we'll do with standalone Focalboard, to the community to maintain.

**Comment by alerque** [comment]
Thanks for that clarification @jwilander. That's pretty good news from my point of view.

**Comment by DerekJarvis** [comment]
Is there any update on this? I'm in the process of moving focalboard data to a new server and came across a number of issues - some of which I have solutions to. The state of the open issues in this repository doesn't encourage people to contribute to this project. I enjoy mattermost and focalboards together and it'd be a shame to ditch focalboard for something less integrated.

**Comment by jwilander** [comment]
Hi all, the [steps I mentioned above](https://github.com/mattermost-community/focalboard/issues/4875#issuecomment-2248824172) are now complete.

The Mattermost Boards plugin now lives here: https://github.com/mattermost/mattermost-plugin-boards

This repository now only contains the standalone Focalboard. If someone is interested in maintaining this repository please [let us know here](https://github.com/mattermost-community/focalboard/issues/5038).
